#!/bin/bash
# Swaync semicolons and colons parsing seems to be broken, 
# that's why there is a separate script for it

if [[ "$MANGO_INSTANCE_SIGNATURE" ]]; then
    mmsg dispatch spawn, "alacritty -e htop"
else
    hyprctl eval "hl.exec_cmd('alacritty -e htop')"
fi

swaync-client -cp
